### PR TITLE
implemented nautical miles type and formatter

### PR DESCRIPTION
**Pull request by steveneal**
Hi. Here's the fork. Sorry for the confusion I've not done a fork using GitHub before.

Let me know if this works.

### CODE REVIEW

**Comment by zhenyanghua** [comment]
I checked the wiki page for [nautical units](https://en.wikipedia.org/wiki/Nautical_mile), it describes a different unit than what you proposed in this PR. 

In your PR commits:
- the unit conversion is different from what's on the linked page for nautical mile
- the unit symbol is not implemented to reflect the use of the nautical mile.

Please make adjustments to the above issues and we will review again.

Thanks!

**Comment by zhenyanghua** [comment]
I don't see the committed changes in the source file but only compiled file, could you push again to the source? Thanks

**Comment by steveneal** [comment]
I don't understand the build for this project, hence I updated the compiled version.

I've added the changes to the helper.js file now, but cannot test that it builds without some instruction on running the build. I've looked but can't see any dev documentation for this.

Thx.

**Comment by zhenyanghua** [comment]
You could just execute `npm run dev` to test it in your local dev env. You don't need to run build, it will cause unnecessary overhead to the commit.

**Comment by railsGod** [comment]
@steveneal i could use nautical miles too, can you please share the code?

**Comment by railsGod** [comment]
@zhenyanghua hi, is there any issue remaining that prevents merging? i could use the the nautical miles as well ...

**Comment by steveneal** [comment]
As far as I'm concerned this is working. I'm not sure why it hasn't been
merged in.

**Comment by railsGod** [comment]
Yeah the code looks valid, there is nothing wrong with measuring in meters and then converting -- can you please send me your combined .js?

**Comment by zhenyanghua** [comment]
Sorry guys for the delay. I just took a look at the helper.js PR and found there is some minor refactoring needs to be done to fit into the existing ES6 code style and reuse the existing classes and test it before I can merge to the master. Hopefully I will be able to work on this project this weekend.

**Comment by railsGod** [comment]
Excellent, thank you!

**Pull request merged**
